// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWIFHTwtnz-Lhc3-9XcK7qTqiEzmXgM4',
    appId: '1:234611071510:web:f7aedabea57abf9bdeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    authDomain: 'chem-manager.firebaseapp.com',
    storageBucket: 'chem-manager.firebasestorage.app',
    measurementId: 'G-EL67MMGGRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCgGQjo4C6kuNvk8h3m3GrGiWWf4vmnQ',
    appId: '1:234611071510:android:2c33bcd2822ae7a7deb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXj8cHFFSrYU9fKLh3LRAarngACV8pJMQ',
    appId: '1:234611071510:ios:6bf4aca6c1e7d0d9deb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
    iosBundleId: 'com.example.chemManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXj8cHFFSrYU9fKLh3LRAarngACV8pJMQ',
    appId: '1:234611071510:ios:6bf4aca6c1e7d0d9deb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    storageBucket: 'chem-manager.firebasestorage.app',
    iosBundleId: 'com.example.chemManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOWIFHTwtnz-Lhc3-9XcK7qTqiEzmXgM4',
    appId: '1:234611071510:web:296ca120f180177cdeb337',
    messagingSenderId: '234611071510',
    projectId: 'chem-manager',
    authDomain: 'chem-manager.firebaseapp.com',
    storageBucket: 'chem-manager.firebasestorage.app',
    measurementId: 'G-ZDQLWP4KZP',
  );
}
